version: '3'
services:
  node:
    build: ./server
    depends_on:
      - couchdb
    container_name: node
    ports:
      - "80:8080"
    volumes:
      - ./server:/usr/src/app

  couchdb:
    image: couchdb:3.2.0
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
